version: "3.5"

services:
  frontend:
    image: node:12-alpine
    working_dir: /app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - NODE_ENV=development
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./frontend:/app

  backend:
    image: node:12-alpine
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3000
    command: npm start
    volumes:
      - ./backend:/app
